name: QR Generator
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - uses: snow-actions/qrcode@v1.0.0
      with:
        text: www.linkedin.com/in/rahman150204
        path: qrcode.png
    - name: You can upload it to artifact.
      uses: actions/upload-artifact@v1
      with:
        name: qrcode
        path: qrcode.png